### PR TITLE
Styling bid

### PR DESCRIPTION
**Pull request by michaltakac**
screen shot 2017-12-13 at 12 31 31

### CODE REVIEW

**Comment by abarmat** [comment]
Hey Michal, the bid modal looks good. I have a couple of comments:

1) Maybe it would be good to center the box vertically I think it looks better. What do you think?

center
top

2) I see that the green color of the button is different from the mockup.

**Comment by abarmat** [comment]
The button has the right color only when I set the focus on it.

focus

**Comment by michaltakac** [comment]
1. Yup will align it vertically, looks much better :)
2. At first I used color from mockup but then changed it to the green color we use in `PendingConfirmationBidsTable` (https://github.com/decentraland/auction/pull/79/commits/5a631aa3c4b87786abb2217cef2bd8bf0f418f6d). Changing back to the one from mockup (what do you think about changing the color in `PendingConfirmationBidsTable` as well @abarmat @NicoSantangelo @eordano?

**Comment by abarmat** [comment]
Yes, let's change the color. In the last mockup it is using the light green.

pending

**Comment by abarmat** [comment]
Michal, one more thing. The vertical centering is breaking the intro modal.

broken-modal

**Comment by michaltakac** [comment]
Oh shoot! Fix incoming...

**Comment by abarmat** [comment]
Lovely!

**Pull request merged**
