### PR TITLE
Stats redesign

### PR DESCRIPTION
**Pull request by nicosantangelo**
localhost_3000_stats

### CODE REVIEW

**Comment by abarmat** [comment]
This is an edge case which will not happen in prod but if we have no bids on parcels and all the endAt fields are NULL we get the following error.

stats

**Comment by nicosantangelo** [comment]
I actually came across this and forgot about it later. Will fix, as soon as I finish up some styles in the other branch. I'll let you know

**Comment by abarmat** [comment]
@NicoSantangelo perfect!

**Comment by nicosantangelo** [comment]
Updated!

**Pull request merged**
