### PR TITLE
Add more margin so that borders are not shown in gray

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Comment by nicosantangelo** [comment]
I think an easier implementation would be to change the `onMoveEnd` method on ParcelMapContainer. That method requests the new parcels to be fetched, and uses an offset for performance reasons, but it's easily removed!

From:

```javascript
  onMoveEnd = ({ position, bounds }) => {
    const offset = this.getBoundsOffset() // <--- HERE! this is the offset to remove (and the method it get's it from)

    this.fetchParcelRange(
      bounds.min.x + offset,
      bounds.min.y + offset,
      bounds.max.x - offset,
      bounds.max.y - offset
    )

    this.props.changeLocation(locations.parcelDetail(position.x, position.y))
  }
```

What do you think?

**Comment by eordano** [comment]
Sounds good!
I used the same value, but instead of preventing fetch inwards, it fetches outwards. See https://github.com/decentraland/auction/pull/44/files#diff-b3568e38d667e8e859e4fd004ce0858b

**Comment by nicosantangelo** [comment]
Awesome! trying it out

**Comment by nicosantangelo** [comment]
I would've flipped the values here:

```javascript
this.state.zoom - this.baseZoom
``` 

but it's a minor thing, merging!

**Pull request merged**
