### PR TITLE
Parcel color review

### PR DESCRIPTION
**Pull request by eordano**
Fixes:

- Calculation of color (yellow -> red!)
- Memorize calculation of color for performance
- Better reducer to incorporate new parcel states
- Hardwire project names for Genesis Plaza and Roads
- Docker change that caused DB to be reset

### CODE REVIEW

**Comment by abarmat** [comment]
I started from scratch, bid for 6 parcels of LAND on account-1 and when I switch to account-2 it shows wrong colors. Shouldn't they be yellow?

account1
account2

**Update:**
I tried again, did refresh a couple of time the page and showed them right. Seems some sort of caching problem.

**Comment by abarmat** [comment]
Is it necessary to hardwire the Genesis Plaza and Road projects ids? Maybe we could use the project names instead as we have under control that districts are not duplicated.

**Comment by abarmat** [comment]
I tried zooming in and the color changed, attached an animation.
cache

**Comment by eordano** [comment]
> Is it necessary to hardwire the Genesis Plaza and Road projects ids? Maybe we could use the project names instead as we have under control that districts are not duplicated.

It's more efficient. I'd rather pass in one parameter less (the parcel only contains the project id, not the project name)

**Comment by abarmat** [comment]
Working now!

**Pull request merged**
