### PR TITLE
Add an edit action to the pending confirmation bids. …

### PR DESCRIPTION
**Pull request by nicosantangelo**
Also fixex address balance after confirm fail

### CODE REVIEW

**Comment by abarmat** [comment]
Works flawlessly! I have two observations, tell me your thoughts.

1) I think design-wise the buttons for the delete and edit are a bit too small I would make them bigger.
2) When I edit a bid and submit, the entry goes down the list instead of sitting in its position, it's a bit confusing.

**Comment by nicosantangelo** [comment]
@abarmat 

> 1) I think design-wise the buttons for the delete and edit are a bit too small I would make them bigger.

Agreed! updating it now

> 2) When I edit a bid and submit, the entry goes down the list instead of sitting in its position, it's a bit confusing.

I do agree but it's a bit of a pain to implement. Let me give it a try and report back!

**Comment by nicosantangelo** [comment]
Updated!

**Comment by eordano** [comment]
image
I'd make the header say "Action" and get some better icons. But that can be done in another PR after feedback from trevor. merging this.

**Pull request merged**
