### PR TITLE
Reposition help button

### PR DESCRIPTION
**Pull request by abarmat**

### CODE REVIEW

**Comment by nicosantangelo** [comment]
The collapsed sidebar works great, but when I open it it looks weird:

image

-------------------

image

-------------------

sidebar

(this last one may not be that bad, resolutions these days are quite good)

**Comment by abarmat** [comment]
Maybe instead of floating it like the minimap it should just sit in the div and have a version for the collapsed and expanded one.

**Comment by abarmat** [comment]
How does it look now? Some thoughts:

1) I think it is less odd than the previous version.
2) I don't like that much a circle in the expanded version, maybe it could just be a text?
3) We can additionally use the DCL logo which is not clickeable and open the help.

**Comment by nicosantangelo** [comment]
A few things:

- I think it's a good opportunity to fix the positioning of the shift modal. We can do something like this:

sidebar

to do that I added:

```css
.top-controls {
  + height: 100%;
  + position: relative;
}

.ShiftNotification {
- left: 70px;
+ left: 10px;
}
```

and moved the `ShiftNotification` component inside the div with the `top-controls` class

- I like the new expanded `?` **much** more. Nice work. I do agree with the border thought. I think it'll look better without it and with even spacing from the top and bottom elements:

image

- I think the old collapsed version looked a bit better, with the `?` on the bottom. What do you think?

**Comment by nicosantangelo** [comment]
I like it! but even thought I know I'm annoying, trying it out with an address that has a lot of bids hides the `?` button, which might not be what we want.

So I was thinking, what if we put it on the sidebar header:

image

OR

image

The good thing about this option is that the header follows you when you scroll the sidebar?

What do you think? If you like the idea I opened a PR against this branch with the first images implementation (with the border) here: #89
Feel free to close it otherwise.

**Comment by nicosantangelo** [comment]
Oh! and one more thing.

Clicking the help button toggles the sidebar, which shouldn't happen.

**Comment by abarmat** [comment]
I like it better on top (with the circle), it's a bit more like a button.

**Comment by abarmat** [comment]
Done both changes. Thank you!

**Pull request merged**
