### PR TITLE
New expanded and collapsed sidebar

### PR DESCRIPTION
**Pull request by nicosantangelo**
image

image

### CODE REVIEW

**Comment by abarmat** [comment]
The sidebar is looking great! I see that when I want to add a new bid the pending bids box is broken looking all white.

pending bids

**Comment by abarmat** [comment]
Maybe we can also text-align: center; the dashboard heading and values I think it looks better, what do you think?

before
after

**Comment by nicosantangelo** [comment]
Bug fixed!

what do you think of this?

image


lined

I lined it up with the table below

**Comment by abarmat** [comment]
Pending confirmations are back, great! I like the new proposed alignment better, but don't see it done in the last committed version.

**Comment by abarmat** [comment]
Other than that is ready to merge.

**Comment by nicosantangelo** [comment]
Weird, you're right.
re-adding

**Comment by nicosantangelo** [comment]
Updated @abarmat !

**Pull request merged**
