### PR TITLE
Clear all bids

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Comment by eordano** [comment]
Probably needs more design

image

**Comment by abarmat** [comment]
Works perfectly! but it was hard for me to find the X button. We could add a cancel or clear button, what do you think?
clear

**Comment by nicosantangelo** [comment]
Agree with @abarmat. Another option is maybe make it be a red `clear` on the top right instead of a `x`

**Comment by eordano** [comment]
image
Updated

**Comment by nicosantangelo** [comment]
@eordano Cool! works great.

Tiny question, don't you think it might be better if we add a `confirm` on the clear all action? I'm not sure but might be useful

**Comment by eordano** [comment]
Added

**Pull request merged**
