### PR TITLE
Address stats redesign

### PR DESCRIPTION
**Pull request by nicosantangelo**

### CODE REVIEW

**Comment by abarmat** [comment]
The date string is getting on the same line with the address. I think it will look better if we move it to a new line. What do you think?

date

**Comment by eordano** [comment]
Fixed @abarmat's comment

**Comment by abarmat** [comment]
Alternatively, we can fix by CSS with: 

```
.AddressStats .Definition dt a {
  display: block;
  font-weight: normal;
}
```

**Comment by abarmat** [comment]
@eordano I see the same problem happening with the &nbsp;

I'll push the CSS change.

**Comment by abarmat** [comment]
I think it looks better in a new line.

css

**Pull request merged**
