### PR TITLE
Change the way errors are reported from the server and reflect the UI

### PR DESCRIPTION
**Pull request by nicosantangelo**
Complex changes, need a new set of eyes to check it out

### CODE REVIEW

**Comment by eordano** [comment]
Nice overhaul. @michaltakac maybe you can help review this since you're also very experienced with redux?

**Comment by eordano** [comment]
@michaltakac can you help reviewing this?

**Comment by michaltakac** [comment]
Went through 3/4 so far, so far so good, will finish when I wake up.

**Comment by abarmat** [comment]
I forced a couple of errors, the server seems to be passing the information back to the UI correctly. 
However, I think we can improve a little bit the formatting, maybe printing one error per line of bids submitted?

display

**Pull request merged**
