### PR TITLE
Email notification frontend

### PR DESCRIPTION
**Pull request by abarmat**

### CODE REVIEW

**Comment by nicosantangelo** [comment]
Will take a look later today!

**Comment by eordano** [comment]
When I don't have any bids, I get the following error:

```
api_1       | [[Server]] Handling request to /api/outbidNotification
api_1       | [[Server]] Error handling request /api/outbidNotification Error: Could not get parcelStateIds from request
api_1       |     at Object.extractFromReq (/usr/src/app/node_modules/decentraland-commons/dist/server/index.js:91:11)
api_1       |     at _callee3$ (/usr/src/app/src/server.js:179:33)
api_1       |     at tryCatch (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
api_1       |     at Generator.invoke [as _invoke] (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
api_1       |     at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
api_1       |     at step (/usr/src/app/src/server.js:283:191)
api_1       |     at /usr/src/app/src/server.js:283:437
api_1       |     at new Promise (<anonymous>)
api_1       |     at /usr/src/app/src/server.js:283:99
api_1       |     at postOutbidNotification (/usr/src/app/src/server.js:207:18)
api_1       |     at Object._callee$ (/usr/src/app/node_modules/decentraland-commons/dist/server/index.js:39:22)
api_1       |     at tryCatch (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
api_1       |     at Generator.invoke [as _invoke] (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
api_1       |     at Generator.prototype.(anonymous function) [as next] (/usr/src/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
api_1       |     at step (/usr/src/app/node_modules/decentraland-commons/dist/server/index.js:11:191)
api_1       |     at /usr/src/app/node_modules/decentraland-commons/dist/server/index.js:11:437
```

**Comment by abarmat** [comment]
Fixed the problem when empty ongoing bids.

**Comment by nicosantangelo** [comment]
Mini-issue with `Button` props:

image

@abarmat

**Comment by nicosantangelo** [comment]
while re-subscribing is really easy, I think it might be worth wile adding a `confirm` to the action. What do you guys think?

**Comment by nicosantangelo** [comment]
Last thing! a little feedback on the styling:

- I think that the `You're subscribed` text can be a bit distracting after a while, and can be toned down a bit having a `font-size` of `15px` and reducing the unsubscribe button padding and moving it to the right like this:
image

- Another way to do draw less attention to the unsubscribe is changing it to a link (instead of a button, like this:
clipboard - november 28 2017 7-45 pm

I don't mean for any of this to *be* the right way but as a discussion

---------

That's it, great job!

**Comment by abarmat** [comment]
All recommendations submitted!

**Pull request merged**
