### PR TITLE
Parallel requests

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Comment by nicosantangelo** [comment]
We need a rebase!

**Comment by eordano** [comment]
Rebas'd

**Comment by michaltakac** [comment]
This is nice!

**Comment by nicosantangelo** [comment]
This will sadly conflict with #126, but I'll do the rebase once that's merged!

**Comment by eordano** [comment]
I'll do the rebase later

**Comment by abarmat** [comment]
Good idea

**Pull request merged**
